1) Create numpy array and perform following operation > Convert 1D array to 2D > Print Array Attributes(Like shape, dimenssion, data type, itemsize) > Create a 3×3 NumPy array of all 9 > Create a 1D array of 10 evenly spaced values between 25 and 125 > Convert a Python list into a NumPy array > Reverse a 1D NumPy array > Create a 4×4×3 array and extract value at its second set, first row and last column > Create a 4×4 and Extract Odd Rows and Even Columns > Slice the first two rows and first two columns of econd set from a 4×4×3 array > Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]] > Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4] > Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element. Multiply two NumPy arrays element by element. > Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]

In [9]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])
print("1D:\n",arr)

arr.shape = (3,3)
print("2D:\n", arr)

1D:
 [1 2 3 4 5 6 7 8 9]
2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)

(3, 3)
2
int64
8


In [14]:
arr = np.empty((3,3))
arr.fill(9)
arr

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [17]:
arr = np.linspace(25, 125, 10)
arr

array([ 25.        ,  36.11111111,  47.22222222,  58.33333333,
        69.44444444,  80.55555556,  91.66666667, 102.77777778,
       113.88888889, 125.        ])

In [18]:
l = [1,2,3,4]
arr = np.array(l)
print(type(l))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [32]:
arr = np.arange(1, 49)
arr.shape = (4,4,3)
print(arr)

print("\n\n2 set , 1 row, last column: ", arr[1, 0, -1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]


2 set , 1 row, last column:  15


In [30]:
arr1 = np.arange(1, 17)
arr1.shape = (4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
print(arr1[::2, 1::2])

[[ 2  4]
 [10 12]]


In [33]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45],
        [46, 47, 48]]])

In [34]:
arr[:,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[13, 14],
        [16, 17]],

       [[25, 26],
        [28, 29]],

       [[37, 38],
        [40, 41]]])

In [36]:
arr = np.array([[23, 56, 78, 93], [71, 82, 13, 24]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 == 1:
            arr[i][j] = -1

print(arr)

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [38]:
non_zero = []
arr = np.array([1, 0, 2, 0, 3, 0, 4])

for i in range(arr.shape[0]):
    if arr[i] != 0:
        non_zero.append(i)
    
non_zero

[0, 2, 4, 6]

In [39]:
a = np.array([10,20,30])
b = np.array([1,2,3])

print("Add: ",a + b)
print("Sub: ",a - b)
print("Mul: ",a * b)
print("Div: ",a / b)

Add:  [11 22 33]
Sub:  [ 9 18 27]
Mul:  [10 40 90]
Div:  [10. 10. 10.]


In [41]:
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

print(arr1 @ arr2)
print(arr1.dot(arr2))

1875
1875
